### PR TITLE
Add general timeout guide for client

### PR DESCRIPTION
**Pull request by hjr3**

### CODE REVIEW

**Comment by seanmonstar** [comment]
@hjr3 thanks for writing this up! I took a poll, and found that the tokio-timer crate is... perhaps, less official... than the the `Timeout` in tokio-core. As the functionality in core is more likely to receive updates or fixes, it's probably better for hyper to "recommend" using it from there.

Not that we're actually saying one is better than the other, but merely being in a guide will be de-facto recommending it. Would it be possible to write this using tokio-core instead of tokio-timer?

**Comment by hjr3** [comment]
@seanmonstar for sure. i thought about doing both. i chose tokio-timer because it was easier to `Timer::timeout` as opposed to a `select2`. That being said, I will change this to use the tokio-core timer.

**Comment by hjr3** [comment]
@seanmonstar updated

**Comment by seanmonstar** [comment]
Thanks!

**Pull request merged**
