### PR TITLE
docs(client): add POST request example to client guide

### PR DESCRIPTION
**Pull request by akneni**
Add a new section to the "Getting Started with a Client" guide that demonstrates how to make POST requests using hyper. The new section includes examples for sending plain text, binary data, and JSON in the request body, along with appropriate Content-Type headers.

This addition helps users understand how to construct and send POST requests, complementing the existing GET request example. This addresses issue [#3411](https://github.com/hyperium/hyper/issues/3411).

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks so so much for helping improve the guides! I really do appreciate it. I notice that in the [0.14 client guides](https://hyper.rs/guides/0.14/client/advanced/), making a POST request was talked about, and it's missing in the 1.0 guides.

However, if you have some availability, I feel it'd be good to plan out a bit more what even should be available in the "client" portion of the guides. As #3411 highlights, there's a basic fetch, and then explaining connectors. What do you think would be a good set of guides under "client"? That we could probably split this work out into a separate page, but follow a logical order to build on a user's learning.

**Comment by akneni** [comment]
@seanmonstar Do you have any comments on the updated version of this PR?

**Review by seanmonstar — COMMENTED** [review]
I like the list of changes to prep the reader! I think we can merge this, the only comment I have now is regarding the name of the guide, since changing it can affect the URL. I know it was called "advanced" before, but I think the name could be improved. There's two options that come to my mind:

1. `/client/post/`
2. `/client/send-data/`

The first one might closer match the terminology someone is thinking off, where the second uses more natural English. I'm open to either, and would appreciate hearing a reason for why one is better than the other.

After that, we can merge 😀

**Comment by akneni** [comment]
No problem, I can make that change. I'm thinking `/client/post/` may be better. I don't think the "natural English" version is too necessary since anyone working with a low level HTTP library will probably know that a post request sends data.

**Review by seanmonstar — APPROVED** [review]

**Pull request merged**
